export enum Role {
  ADMIN = 'ADMIN',
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  TEAM_MEMBER = 'TEAM_MEMBER',
}

export enum AccountStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_PASSWORD_CHANGE = 'PENDING_PASSWORD_CHANGE',
}

export enum ProjectStatus {
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
  COMPLETED = 'COMPLETED',
}

export enum TaskPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum AbsenceStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum NotificationType {
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_DUE_SOON = 'TASK_DUE_SOON',
  TASK_OVERDUE = 'TASK_OVERDUE',
  COMMENT_ADDED = 'COMMENT_ADDED',
  MENTION = 'MENTION',
  ABSENCE_REQUESTED = 'ABSENCE_REQUESTED',
  ABSENCE_APPROVED = 'ABSENCE_APPROVED',
  ABSENCE_REJECTED = 'ABSENCE_REJECTED',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  PROJECT_INVITED = 'PROJECT_INVITED',
  MILESTONE_REACHED = 'MILESTONE_REACHED',
}

export enum AuditAction {
  USER_CREATED = 'USER_CREATED',
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_REACTIVATED = 'USER_REACTIVATED',
  USER_DELETED = 'USER_DELETED',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_PASSWORD_RESET = 'USER_PASSWORD_RESET',
  PROJECT_CREATED = 'PROJECT_CREATED',
  PROJECT_ARCHIVED = 'PROJECT_ARCHIVED',
  PROJECT_DELETED = 'PROJECT_DELETED',
  TASK_CREATED = 'TASK_CREATED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_DELETED = 'TASK_DELETED',
  MEMBER_ADDED = 'MEMBER_ADDED',
  MEMBER_REMOVED = 'MEMBER_REMOVED',
  ABSENCE_SUBMITTED = 'ABSENCE_SUBMITTED',
  ABSENCE_APPROVED = 'ABSENCE_APPROVED',
  ABSENCE_REJECTED = 'ABSENCE_REJECTED',
  ANNOUNCEMENT_CREATED = 'ANNOUNCEMENT_CREATED',
}

export enum DeliverableType {
  DELIVERABLE = 'DELIVERABLE',
  REPORT = 'REPORT',
}
